name: Test dotfiles
run-name: "${{ github.actor }} is testing dotfiles 🚀"
on: [push]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  aws_access_key_id: fake_aws_access_key_id
  aws_secret_access_key: fake_aws_secret_access_key
jobs:
  dotfiles-install:
    runs-on: macos-latest
    steps:
      - name: Set ENV file .zshenv
        run: |
          cp ./dotfiles/dot-zshenv ~/.zshenv
        shell: zsh -e {0}
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Run Makefile file
        run: |
          make
        shell: zsh -e {0}
      - name: Test make results
        run: |
          make test-all
        shell: zsh -e {0}
