name: Test dotfiles
run-name: "${{ github.actor }} is testing dotfiles on:\n${{ github.sha }} 🚀"
on: [push]
jobs:
  dotfiles-install:
    runs-on: macos-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Run Makefile file
        run: make
